'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Security } from '@okta/okta-react';
import { OktaAuth, toRelativeUrl } from '@okta/okta-auth-js';
import { useRouter } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const origin =
        typeof window !== 'undefined' && window.location.origin
            ? window.location.origin
            : '';
  const oktaAuth = new OktaAuth({
    issuer: 'https://id.cisco.com/oauth2/default',
    clientId: '0d6834a4-f38a-4475-87b0-92ab900c3bfb',
    redirectUri: origin + '/login/callback',
    pkce: true,
  });
  const restoreOriginalUri = async (_oktaAuth: any, originalUri: string) => {
    router.push(toRelativeUrl(originalUri || '/', window.location.origin));
  };
  return (
    <Security
      oktaAuth={oktaAuth}
      restoreOriginalUri={restoreOriginalUri}
    >
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </Security>
  );
}
